### ISSUE TITLE
Why define shared_ptr and unique_ptr

### ISSUE THREAD

**Issue by danielruc91** [discretelogics/TeaFiles.Cpp#2]
In the 'Pointer.h', there are 2 functions: `shared` and `unique`, which basically create a shared point and a unique pointer. Why not directly invoke constructor of `std::shared_ptr` and `std::unique_ptr`? Besides clarity, using these 2 functions can have safety issues. Since it requires a raw pointer, the real object can be accessed elsewhere, and potentially be deleted. For example:

``` C++
int* p1 = new int( 42 );
auto p2 = shared( p1 );
delete p1;              // p2 is now dangling.
```

So I am creating this issue to see why it is designed liked this. Thanks.

**Comment by thulka** [comment]
AFAIR, I did the indirection to isolate and collect all smart pointers in Pointer.h . At the time of writing the code, smart pointer in the std library where just evolving I think.

As of today, shared_ptr and unique_ptr are perfectly established and base parts of C++ and I would not do such indirection. Next time I touch the code base, I will remove Pointer.h and use std::shared_ptr and std::unique_ptr directly.

The consequences you draw are not correct. The functions shared() and unique() are certainly inlined by every compiler and vaporize in the binary output - even without an inline hint. The functions are safe, you misunderstood the mechanics off smart pointers. Every smart pointer is a somewhat intelligent (therefore smart) resource managing utility and stores a raw pointer to the resource among maybe other things (like a reference count in case of share_ptr). If you delete the resource with a plain delete call, then the smart pointer points to invalid memory. Such deletion would violate the usage pattern of smart pointers.
