### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by stanleywu111** [discretelogics/TeaFiles.Cpp#3]
warning: mismatched versions of Boost.Build engine and core
warning: Boost.Build engine (bjam) is 2014.03.00
warning: Boost.Build core (at /home/stanleywu/Downloads/boost_1_63_0/tools/build/src) is 2015.07-git
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
notice: could not find main target all
notice: assuming it is a name of file to create.
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/tools/builtin.jam:887: in linking-generator.generated-targets
*** argument error
* rule generator.generated-targets ( sources + : property-set : project name ? )
* called with: (  : object(property-set)@156 : object(project-target)@68 TeaFile )
* missing argument sources
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:536:see definition of rule 'generator.generated-targets' being called
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/tools/unix.jam:67: in generated-targets
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:459: in construct-result
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:412: in run-really
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:386: in generator.run
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/tools/builtin.jam:802: in linking-generator.run
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/tools/unix.jam:41: in unix-linking-generator.run
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/tools/gcc.jam:701: in class@gcc-linking-generator.run
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:994: in try-one-generator-really
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:1056: in try-one-generator
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:1294: in construct-really
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/generators.jam:1378: in generators.construct
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/targets.jam:1553: in construct
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/targets.jam:1353: in class@basic-target.generate
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/targets.jam:774: in generate-really
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/targets.jam:746: in class@main-target.generate
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build/targets.jam:272: in class@project-target.generate
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/build-system.jam:714: in load
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/kernel/modules.jam:295: in import
/home/stanleywu/Downloads/boost_1_63_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build
/home/stanleywu/Dev/TeaFiles.Cpp/boost-build.jam:1: in module scope

**Comment by peterjkrey** [comment]
I have also seen this issue;  workaround seems to be simply use Visual Studio 2010

**Comment by thulka** [comment]
checked in a VS 2015 version. Actually it was sufficient to use the "Retarget" feature from VS 2015.
