### ISSUE TITLE
Add Visual Studio 2015 C++ support

### ISSUE THREAD

**Issue by peterjkrey** [discretelogics/TeaFiles.Cpp#4]
Build on Windows Server 2012 R2 with VS2012 yields:

1>------ Build started: Project: TeaFiles, Configuration: Debug Win32 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
2>------ Build started: Project: Sum, Configuration: Debug Win32 ------
3>------ Build started: Project: AnalyzeTicks, Configuration: Debug Win32 ------
4>------ Build started: Project: CreateTicks, Configuration: Debug Win32 ------
5>------ Build started: Project: TeaFiles.Test, Configuration: Debug Win32 ------
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
========== Build: 0 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========

But when I Retarget solution I get the following build results:
1>------ Rebuild All started: Project: TeaFiles, Configuration: Debug Win32 ------
1>  TimeScale.cpp
1>  Time.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  WinUtils.cpp
1>c:\users\administrator\documents\github\teafiles.cpp\teafiles\os\winutils.cpp(52): error C2220: warning treated as error - no 'object' file generated
1>c:\users\administrator\documents\github\teafiles.cpp\teafiles\os\winutils.cpp(52): warning C4458: declaration of 'message' hides class member
1>  c:\users\administrator\documents\github\teafiles.cpp\teafiles\os\winutils.cpp(52): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
1>  c:\users\administrator\documents\github\teafiles.cpp\teafiles\os\winutils.h(30): note: see declaration of 'teatime::CheckException::message'
1>  HeaderManager.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  FileIO.cpp
1>  FormattedWriter.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  FormattedReader.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  TextUtils.cpp
1>  ItemSectionFormatter.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  ReadContext.cpp
1>  TeaFileDescription.cpp
1>  ItemDescription.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  WriteContext.cpp
1>  TimeSectionFormatter.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  NameValueSectionFormatter.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  ContentSectionFormatter.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  Streams.cpp
1>  Field.cpp
1>  TeaFileCore.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  IO.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  Generating Code...
1>  Compiling...
1>  FieldType.cpp
1>  NameValue.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid_io.hpp(62): error C2220: warning treated as error - no 'object' file generated
1>c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid_io.hpp(62): warning C4456: declaration of 'i' hides previous local declaration
1>  c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid_io.hpp(62): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
1>  c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid_io.hpp(52): note: see declaration of 'i'
1>  c:\users\administrator\documents\github\teafiles.cpp\teafiles\base\namevalue.cpp(46): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &boost::uuids::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const boost::uuids::uuid &)' being compiled
1>  Exceptions.cpp
1>  MemoryAccess.cpp
1>  Unknown compiler version - please run the configure tests and report the results
1>  Generating Code...
2>------ Rebuild All started: Project: Sum, Configuration: Debug Win32 ------
3>------ Rebuild All started: Project: AnalyzeTicks, Configuration: Debug Win32 ------
4>------ Rebuild All started: Project: CreateTicks, Configuration: Debug Win32 ------
5>------ Rebuild All started: Project: TeaFiles.Test, Configuration: Debug Win32 ------
2>  Sum.cpp
4>  CreateTicks.cpp
3>  Analyze.cpp
2>  Unknown compiler version - please run the configure tests and report the results
5>  TimeTest.cpp
4>  Unknown compiler version - please run the configure tests and report the results
3>  Unknown compiler version - please run the configure tests and report the results
5>  Unknown compiler version - please run the configure tests and report the results
3>c:\users\administrator\documents\github\teafiles.cpp\examples\analyzeticks\analyze.cpp(118): warning C4456: declaration of 'session' hides previous local declaration
3>  c:\users\administrator\documents\github\teafiles.cpp\examples\analyzeticks\analyze.cpp(77): note: see declaration of 'session'
3>LINK : fatal error LNK1104: cannot open file 'TeaFiles32d.lib'
2>LINK : fatal error LNK1104: cannot open file 'TeaFiles32d.lib'
4>LINK : fatal error LNK1104: cannot open file 'TeaFiles32d.lib'
5>  TeaFilesTest.cpp
5>  Unknown compiler version - please run the configure tests and report the results
5>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2983): warning C4996: 'std::equal::_Unchecked_iterators::_Deprecate': Call to 'std::equal' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
5>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2983): note: see declaration of 'std::equal::_Unchecked_iterators::_Deprecate'
5>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(3008): note: see reference to function template instantiation 'bool std::equal<_InIt1,_InIt2,std::equal_to<void>>(_InIt1,_InIt1,_InIt2,_Pr)' being compiled
5>          with
5>          [
5>              _InIt1=boost::uuids::uuid::const_iterator,
5>              _InIt2=boost::uuids::uuid::const_iterator,
5>              _Pr=std::equal_to<void>
5>          ]
5>  c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid.hpp(161): note: see reference to function template instantiation 'bool std::equal<boost::uuids::uuid::const_iterator,boost::uuids::uuid::const_iterator>(_InIt1,_InIt1,_InIt2)' being compiled
5>          with
5>          [
5>              _InIt1=boost::uuids::uuid::const_iterator,
5>              _InIt2=boost::uuids::uuid::const_iterator
5>          ]
5>  Main.cpp
5>  TimeSectionTest.cpp
5>  HeaderManagerTest.cpp
5>  FormattedReaderWriterTest.cpp
5>  Unknown compiler version - please run the configure tests and report the results
5>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2983): warning C4996: 'std::equal::_Unchecked_iterators::_Deprecate': Call to 'std::equal' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
5>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2983): note: see declaration of 'std::equal::_Unchecked_iterators::_Deprecate'
5>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(3008): note: see reference to function template instantiation 'bool std::equal<_InIt1,_InIt2,std::equal_to<void>>(_InIt1,_InIt1,_InIt2,_Pr)' being compiled
5>          with
5>          [
5>              _InIt1=boost::uuids::uuid::const_iterator,
5>              _InIt2=boost::uuids::uuid::const_iterator,
5>              _Pr=std::equal_to<void>
5>          ]
5>  c:\users\administrator\documents\github\teafiles.cpp\lib\boost\uuid\uuid.hpp(161): note: see reference to function template instantiation 'bool std::equal<boost::uuids::uuid::const_iterator,boost::uuids::uuid::const_iterator>(_InIt1,_InIt1,_InIt2)' being compiled
5>          with
5>          [
5>              _InIt1=boost::uuids::uuid::const_iterator,
5>              _InIt2=boost::uuids::uuid::const_iterator
5>          ]
5>  FileIOTest.cpp
5>  TextUtilsTest.cpp
5>  ItemDescriptionTest.cpp
5>  Unknown compiler version - please run the configure tests and report the results
5>  Generating Code...
5>LINK : fatal error LNK1181: cannot open input file 'TeaFiles32d.lib'
========== Rebuild All: 0 succeeded, 5 failed, 0 skipped ==========

Not fun :(

**Comment by thulka** [comment]
Checked in a VS 2015 sln. 
TeaFiles.Test is currently excluded from the solution build.
